<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreOpenAPI30Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreOpenAPI30Lib\Authentication;

use Core\Authentication\CoreAuth;
use SwaggerPetstoreOpenAPI30Lib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;
use SwaggerPetstoreOpenAPI30Lib\CustomHeaderAuthenticationCredentials;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('api_key', $this->getApiKey())->requiredNonEmpty());
    }

    /**
     * String value for apiKey.
     */
    public function getApiKey(): string
    {
        return $this->config['apiKey'] ?? ConfigurationDefaults::API_KEY;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $apiKey
     */
    public function equals(string $apiKey): bool
    {
        return $apiKey == $this->getApiKey();
    }
}
